name: Android Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repozitáře
      uses: actions/checkout@v4

    - name: Nastavení Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Oprávnění ke spuštění Gradlu
      run: chmod +x gradlew

    - name: Sestavení APK přes Gradle
      run: ./gradlew assembleDebug

    - name: Nahrání APK jako artefaktu
      uses: actions/upload-artifact@v4
      with:
        name: termux-launcher-apk
        path: app/build/outputs/apk/debug/app-debug.apk
